### ISSUE TITLE
Edit readme

### ISSUE THREAD

**Issue by MichaelKab** [MichaelKab/OneBigProject#1]
PLease, add text in readme 
"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."

**Comment by VladimirPapazov88** [comment]
Please assign me

**Comment by LebedevKrll** [comment]
Assign me, please
